Repository jline/jline3, pull requests merged in 2024-12, with the labels that each got.

#1122 Fix ConsolePrompt.prompt() throwing IOError instead of UserInterruptedException
  console-ui/src/main/java/org/jline/consoleui/prompt/ConsolePrompt.java
  reader/src/main/java/org/jline/reader/UserInterruptException.java
Labels: bug

#1128 Provide a simple RegistryImpl that can provide options from LineReader
  console/src/main/java/org/jline/console/impl/SimpleSystemRegistryImpl.java
Labels: enhancement

#1127 Enhance DefaultHighlighter to support command styling
  reader/src/main/java/org/jline/reader/impl/DefaultHighlighter.java
Labels: enhancement

#1126 Add style for command description in completer
  builtins/src/main/java/org/jline/builtins/Styles.java
  console/src/main/java/org/jline/console/impl/SystemRegistryImpl.java
Labels: enhancement

#1125 Be more specific about which command is missing when throwing an exception
  console/src/main/java/org/jline/console/impl/AbstractCommandRegistry.java
Labels: enhancement

#1120 Let CommandRegistry create Candidate for completion (fixes #1119)
  console/src/main/java/org/jline/console/CommandRegistry.java
  console/src/main/java/org/jline/console/impl/SystemRegistryImpl.java
  reader/src/main/java/org/jline/reader/impl/completer/SystemCompleter.java
Labels: enhancement

#1130 JLine exec provider should reject terminal creation on a redirected output stream (fixes #1098)
  terminal/src/main/java/org/jline/terminal/impl/exec/ExecTerminalProvider.java
Labels: bug

#1129 Fix build JDK 23
  .github/workflows/master-build.yml
  builtins/src/main/java/org/jline/builtins/ScreenTerminal.java
  demo/src/main/java/org/apache/felix/gogo/jline/Posix.java
  groovy/pom.xml
  jansi-core/src/main/java/org/jline/jansi/Ansi.java
  remote-telnet/src/main/java/org/jline/builtins/telnet/Connection.java
  remote-telnet/src/main/java/org/jline/builtins/telnet/TelnetIO.java
  terminal/src/main/java/org/jline/utils/InputStreamReader.java
Labels: new feature

#1114 InputValue prompt with mask doesn't work correctly, fixes #1103
  console-ui/src/main/java/org/jline/consoleui/prompt/AbstractPrompt.java
  console-ui/src/main/java/org/jline/consoleui/prompt/ConsolePrompt.java
  console-ui/src/main/java/org/jline/consoleui/prompt/InputResult.java
  console-ui/src/main/java/org/jline/consoleui/prompt/PromptResultItemIF.java
Labels: bug

#1131 Add a AbstractTerminal#toString() method
  terminal/src/main/java/org/jline/terminal/impl/AbstractPosixTerminal.java
  terminal/src/main/java/org/jline/terminal/impl/AbstractTerminal.java
Labels: enhancement

#1117 Dynamic console-ui prompts, fixes #1051
  console-ui/jline-console-ui.bat
  console-ui/jline-console-ui.sh
  console-ui/src/main/java/org/jline/consoleui/prompt/ConsolePrompt.java
  console-ui/src/test/java/org/jline/consoleui/Issue1025.java
  console-ui/src/test/java/org/jline/consoleui/examples/Basic.java
  console-ui/src/test/java/org/jline/consoleui/examples/BasicDynamic.java
  console-ui/src/test/java/org/jline/consoleui/examples/LongList.java
  console-ui/src/test/java/org/jline/consoleui/examples/SimpleExample.java
  console-ui/src/test/java/org/jline/consoleui/prompt/PromptBuilderTest.java
Labels: new feature
