Repository jline/jline3, pull requests merged in 2025-07, with the labels that each got.

#1331 chore: make downcall handles static final
  terminal-ffm/src/main/java/org/jline/terminal/impl/ffm/CLibrary.java
Labels: chore

#1327 enhancement: only compute suggestions in the Nano editor if something…
  builtins/src/main/java/org/jline/builtins/Nano.java
Labels: enhancement

#1310 Remove double `docs/docs` in edit links on jline.org (fixes #1309)
  website/docusaurus.config.ts
Labels: chore

#1311 docs: Add Capability.enter_ca_mode and Capability.exit_ca_mode tip
  website/docs/advanced/screen-clearing.md
Labels: documentation

#1312 docs: Link to Nano Customization from Builtins doc page
  website/docs/modules/builtins.md
Labels: documentation

#1333 feat: support slurp command to be renamed
  console/src/main/java/org/jline/console/impl/ConsoleEngineImpl.java
Labels: enhancement

#1341 feat: add reusable POSIX commands to builtins module
  builtins/src/main/java/org/jline/builtins/PosixCommands.java
  builtins/src/main/java/org/jline/builtins/PosixCommandsRegistry.java
  builtins/src/test/java/org/jline/builtins/PosixCommandsTest.java
  builtins/src/test/java/org/jline/builtins/SortComparatorTest.java
  demo/src/main/java/org/apache/felix/gogo/jline/Posix.java
  demo/src/main/java/org/jline/demo/examples/FileOperationsExample.java
  demo/src/main/java/org/jline/demo/examples/PosixCommandsRegistryExample.java
  website/docs/modules/builtins.md
  website/docs/modules/overview.md
Labels: new feature
