Repository jline/jline3, pull requests merged in 2025-08, with the labels that each got.

#1362 Allow ConsoleEngineImpl subclasses access to VariableReferenceCompleter
  console/src/main/java/org/jline/console/impl/ConsoleEngineImpl.java
Labels: enhancement

#1357 ConsoleEngineImpl: change method and field visibilities
  console/src/main/java/org/jline/console/impl/ConsoleEngineImpl.java
Labels: enhancement

#1382 Fix macOS hang in pipe operations by removing PTY terminal usage
  console/src/main/java/org/jline/console/impl/SystemRegistryImpl.java
  console/src/test/java/org/jline/console/impl/SystemRegistryImplTest.java
Labels: bug

#1383 Upgrade to Maven model 4.1.0
  builtins/pom.xml
  console-ui/pom.xml
  console/pom.xml
  curses/pom.xml
  demo/pom.xml
  graal/pom.xml
  groovy/pom.xml
  jansi-core/pom.xml
  jansi/pom.xml
  jline/pom.xml
  native/pom.xml
  pom.xml
  reader/pom.xml
  remote-ssh/pom.xml
  remote-telnet/pom.xml
  style/pom.xml
  terminal-ffm/pom.xml
  terminal-jansi/pom.xml
  terminal-jna/pom.xml
  terminal-jni/pom.xml
  terminal/pom.xml
Labels: build

#1390 PosixCommands.grep incorrect context logic #1389
  builtins/src/main/java/org/jline/builtins/PosixCommands.java
  builtins/src/test/java/org/jline/builtins/PosixCommandsTest.java
Labels: bug

#1387 Catch UnsupportedOperationException or further windows handling is ne…
  builtins/src/main/java/org/jline/builtins/PosixCommands.java
Labels: bug

#1400 builtins PosixCommands ls, cat, grep commands don't handle glob arguments #1399
  builtins/src/main/java/org/jline/builtins/PosixCommands.java
  builtins/src/test/java/org/jline/builtins/PosixCommandsTest.java
Labels: bug

#1407 fix: clean up posix commands and improve ls formatting
  builtins/src/main/java/org/jline/builtins/PosixCommands.java
  builtins/src/main/java/org/jline/builtins/Source.java
Labels: chore
