Repository jline/jline3, pull requests merged in 2025-05, with the labels that each got.

#1229 Enhanced MouseSupport to handle multiple mouse event formats (SGR, URXVT, SGR-Pixels)
  terminal/src/main/java/org/jline/terminal/impl/AbstractTerminal.java
  terminal/src/main/java/org/jline/terminal/impl/MouseSupport.java
  terminal/src/main/java/org/jline/utils/InfoCmp.java
  terminal/src/test/java/org/jline/terminal/impl/MouseSupportTest.java
  terminal/src/test/java/org/jline/utils/InfoCmpTest.java
Labels: new feature

#1243 docs: add syntax highlighting example classes for documentation
  demo/src/main/java/org/jline/demo/examples/BasicHighlighterExample.java
  demo/src/main/java/org/jline/demo/examples/ErrorHighlightingExample.java
  demo/src/main/java/org/jline/demo/examples/KeywordHighlighterExample.java
  demo/src/main/java/org/jline/demo/examples/SyntaxHighlighterExample.java
Labels: doc

#1251 docs: integrate ConsoleUI documentation into website
  README.md
  console-ui/README.md
  console-ui/doc/ConsoleUI-Logo-small.png
  console-ui/doc/ConsoleUI-Logo.svg
  console-ui/doc/howto.md
  demo/src/main/java/org/jline/demo/examples/ConsoleUIExample.java
  website/docs/intro.md
  website/docs/modules/console-ui.md
  website/docs/modules/overview.md
  website/docs/remote-terminals.md
  website/docs/troubleshooting.md
  website/docusaurus.config.ts
  website/src/components/VersionDisplay.tsx
  website/src/pages/javadoc.tsx
  website/static/img/ConsoleUI-Logo.png
  website/static/img/console-ui/checkbox_prompt.png
  website/static/img/console-ui/confirmation_prompt.png
  website/static/img/console-ui/expandable_choice_prompt_1.png
  website/static/img/console-ui/expandable_choice_prompt_2.png
  website/static/img/console-ui/expandable_choice_prompt_3.png
  website/static/img/console-ui/input_prompt.png
  website/static/img/console-ui/list_prompt.png
Labels: docs

#1257 docs: Add picocli links to library integration
  website/docs/advanced/library-integration.md
Labels: docs

#1255 chore: Make ConfigurationPath fields final
  builtins/src/main/java/org/jline/builtins/ConfigurationPath.java
Labels: chore

#1261 fix: Update LineReaderImpl to use new readMouseEvent signature with lastBinding parameter
  reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java
Labels: bug

#1263 chore: Add suitable .vscode/
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
Labels: chore

#1266 docs: fix javadoc redirect URL issue
  website/src/pages/javadoc.tsx
Labels: documentation

#1264 chore: Add DevContainer JSON
  .devcontainer/devcontainer.json
Labels: chore

#1262 docs: integrate GitHub wiki content into website documentation
  demo/src/main/java/org/jline/demo/examples/AutoIndentationExample.java
  demo/src/main/java/org/jline/demo/examples/AutopairWidgetsExample.java
  demo/src/main/java/org/jline/demo/examples/AutosuggestionWidgetsExample.java
  demo/src/main/java/org/jline/demo/examples/BasicStylingExample.java
  demo/src/main/java/org/jline/demo/examples/ConsoleScriptExample.java
  demo/src/main/java/org/jline/demo/examples/CustomKeyBindingsExample.java
  demo/src/main/java/org/jline/demo/examples/CustomPromptExample.java
  demo/src/main/java/org/jline/demo/examples/CustomWidgetsClassExample.java
  demo/src/main/java/org/jline/demo/examples/FileNameCompleterExample.java
  demo/src/main/java/org/jline/demo/examples/FileOperationsExample.java
  demo/src/main/java/org/jline/demo/examples/GroovyScriptExample.java
  demo/src/main/java/org/jline/demo/examples/HighlighterExample.java
  demo/src/main/java/org/jline/demo/examples/KeyBindingExample.java
  demo/src/main/java/org/jline/demo/examples/NanoLessCustomizationExample.java
  demo/src/main/java/org/jline/demo/examples/RegexCompleterExample.java
  demo/src/main/java/org/jline/demo/examples/ReplConsoleExample.java
  demo/src/main/java/org/jline/demo/examples/SimpleLineReadingExample.java
  demo/src/main/java/org/jline/demo/examples/StyleExpressionExample.java
  demo/src/main/java/org/jline/demo/examples/StyleResolverExample.java
  demo/src/main/java/org/jline/demo/examples/StylerExample.java
  demo/src/main/java/org/jline/demo/examples/SystemRegistryExample.java
  demo/src/main/java/org/jline/demo/examples/TailTipWidgetsExample.java
  demo/src/main/java/org/jline/demo/examples/ThemeSystemExample.java
  reader/src/main/java/org/jline/reader/LineReader.java
  website/docs/advanced/auto-indentation-pairing.md
  website/docs/advanced/autosuggestions.md
  website/docs/advanced/nano-less-customization.md
  website/docs/advanced/theme-system.md
  website/docs/history.md
  website/docs/line-reader.md
  website/docs/modules/repl-console.md
  website/docs/reference/diagnostic.md
  website/docs/reference/glossary.md
  website/docs/terminal.md
  website/sidebars.ts
Labels: documentation

#1270 docs: add missing @since 3.30.0 annotations to new methods in Terminal
  terminal/src/main/java/org/jline/terminal/Terminal.java
Labels: documentation

#1272 docs: validate code snippets during build time instead of runtime
  website/package.json
  website/scripts/validate-snippets.js
  website/src/components/CodeSnippet.js
Labels: documentation

#1281 Fix missing close in PosixSysTerminal.
  terminal/src/main/java/org/jline/terminal/impl/PosixSysTerminal.java
Labels: bug

#1287 Fix flaky DumbTerminalPasswordTest
  reader/src/test/java/org/jline/reader/impl/DumbTerminalPasswordTest.java
Labels: chore

#1286 chore: Fix build.bat syntax errors and preserve arguments in rebuild command
  build.bat
Labels: chore

#1283 [consoleui] Make prompts work in non-fullscreen mode
  console-ui/src/main/java/org/jline/consoleui/prompt/AbstractPrompt.java
  console-ui/src/main/java/org/jline/consoleui/prompt/ConsolePrompt.java
Labels: enhancement

#1284 Add support for separate encodings for stdin, stdout, and stderr
  terminal-ffm/src/main/java/org/jline/terminal/impl/ffm/FfmTerminalProvider.java
  terminal-ffm/src/main/java/org/jline/terminal/impl/ffm/NativeWinSysTerminal.java
  terminal-ffm/src/test/java/org/jline/terminal/impl/ffm/FfmTest.java
  terminal-jansi/src/main/java/org/jline/terminal/impl/jansi/JansiTerminalProvider.java
  terminal-jansi/src/main/java/org/jline/terminal/impl/jansi/win/JansiWinSysTerminal.java
  terminal-jansi/src/test/java/org/jline/terminal/impl/jansi/JansiTerminalProviderTest.java
  terminal-jna/src/main/java/org/jline/terminal/impl/jna/JnaTerminalProvider.java
  terminal-jna/src/main/java/org/jline/terminal/impl/jna/win/JnaWinSysTerminal.java
  terminal-jna/src/test/java/org/jline/terminal/impl/jna/JnaTerminalProviderTest.java
  terminal-jni/src/main/java/org/jline/terminal/impl/jni/JniTerminalProvider.java
  terminal-jni/src/main/java/org/jline/terminal/impl/jni/win/NativeWinSysTerminal.java
  terminal-jni/src/test/java/org/jline/terminal/impl/jni/JniTerminalProviderTest.java
  terminal/src/main/java/org/jline/terminal/Terminal.java
  terminal/src/main/java/org/jline/terminal/TerminalBuilder.java
  terminal/src/main/java/org/jline/terminal/impl/AbstractPosixTerminal.java
  terminal/src/main/java/org/jline/terminal/impl/AbstractTerminal.java
  terminal/src/main/java/org/jline/terminal/impl/AbstractWindowsTerminal.java
  terminal/src/main/java/org/jline/terminal/impl/Diag.java
  terminal/src/main/java/org/jline/terminal/impl/DumbTerminal.java
  terminal/src/main/java/org/jline/terminal/impl/DumbTerminalProvider.java
  terminal/src/main/java/org/jline/terminal/impl/ExternalTerminal.java
  terminal/src/main/java/org/jline/terminal/impl/LineDisciplineTerminal.java
  terminal/src/main/java/org/jline/terminal/impl/PosixPtyTerminal.java
  terminal/src/main/java/org/jline/terminal/impl/PosixSysTerminal.java
  terminal/src/main/java/org/jline/terminal/impl/exec/ExecTerminalProvider.java
  terminal/src/main/java/org/jline/terminal/spi/TerminalProvider.java
  terminal/src/test/java/org/jline/terminal/EncodingTest.java
  terminal/src/test/java/org/jline/terminal/MultiEncodingTerminalTest.java
Labels: enhancement

#1305 fix: fix Jansi AnsiConsole broken color detection in uber jars
  jansi-core/src/main/java/org/jline/jansi/AnsiConsole.java
Labels: bug
